# Generated by Django 3.2.8 on 2021-10-24 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0004_post_project_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='project_desc',
        ),
    ]
